[window]
padding = { x = 10, y = 10 }
dynamic_padding = true
opacity = 0.8
#decorations = "None"
dimensions = {columns = 120, lines = 45}
title = "Terminal"

[font]
normal = { family = "Agave Nerd Font", style = "Regular" }
size = 14

# Frappe
#[colors.primary]
#background = "#303446"
#foreground = "#c6d0f5"
#dim_foreground = "#838ba7"
#bright_foreground = "#c6d0f5"
#
#[colors.cursor]
#text = "#303446"
#cursor = "#f2d5cf"
#
#[colors.vi_mode_cursor]
#text = "#303446"
#cursor = "#babbf1"
#
#[colors.search.matches]
#foreground = "#303446"
#background = "#a5adce"
#
#[colors.search.focused_match]
#foreground = "#303446"
#background = "#a6d189"
#
#[colors.footer_bar]
#foreground = "#303446"
#background = "#a5adce"
#
#[colors.hints.start]
#foreground = "#303446"
#background = "#e5c890"
#
#[colors.hints.end]
#foreground = "#303446"
#background = "#a5adce"
#
#[colors.selection]
#text = "#303446"
#background = "#f2d5cf"
#
#[colors.normal]
#black = "#51576d"
#red = "#e78284"
#green = "#a6d189"
#yellow = "#e5c890"
#blue = "#8caaee"
#magenta = "#f4b8e4"
#cyan = "#81c8be"
#white = "#b5bfe2"
#
#[colors.bright]
#black = "#626880"
#red = "#e78284"
#green = "#a6d189"
#yellow = "#e5c890"
#blue = "#8caaee"
#magenta = "#f4b8e4"
#cyan = "#81c8be"
#white = "#a5adce"
#
#[[colors.indexed_colors]]
#index = 16
#color = "#ef9f76"
#
#[[colors.indexed_colors]]
#index = 17
#color = "#f2d5cf"

# mocha
#[colors.primary]
#background = "#1e1e2e"
#foreground = "#cdd6f4"
#dim_foreground = "#7f849c"
#bright_foreground = "#cdd6f4"
#
#[colors.cursor]
#text = "#1e1e2e"
#cursor = "#f5e0dc"
#
#[colors.vi_mode_cursor]
#text = "#1e1e2e"
#cursor = "#b4befe"
#
#[colors.search.matches]
#foreground = "#1e1e2e"
#background = "#a6adc8"
#
#[colors.search.focused_match]
#foreground = "#1e1e2e"
#background = "#a6e3a1"
#
#[colors.footer_bar]
#foreground = "#1e1e2e"
#background = "#a6adc8"
#
#[colors.hints.start]
#foreground = "#1e1e2e"
#background = "#f9e2af"
#
#[colors.hints.end]
#foreground = "#1e1e2e"
#background = "#a6adc8"
#
#[colors.selection]
#text = "#1e1e2e"
#background = "#f5e0dc"
#
#[colors.normal]
#black = "#45475a"
#red = "#f38ba8"
#green = "#a6e3a1"
#yellow = "#f9e2af"
#blue = "#89b4fa"
#magenta = "#f5c2e7"
#cyan = "#94e2d5"
#white = "#bac2de"
#
#[colors.bright]
#black = "#585b70"
#red = "#f38ba8"
#green = "#a6e3a1"
#yellow = "#f9e2af"
#blue = "#89b4fa"
#magenta = "#f5c2e7"
#cyan = "#94e2d5"
#white = "#a6adc8"
#
#[[colors.indexed_colors]]
#index = 16
#color = "#fab387"
#
#[[colors.indexed_colors]]
#index = 17
#color = "#f5e0dc"

# Kanagawa Wave Alacritty Colors

[colors.primary]
background = '#1f1f28'
foreground = '#dcd7ba'

[colors.normal]
black = '#090618'
red = '#c34043'
green = '#98bb6c'
yellow = '#c0a36e'
blue = '#7e9cd8'
magenta = '#957fb8'
cyan = '#6a9589'
white = '#c8c093'

[colors.bright]
black = '#727169'
red = '#e82424'
green = '#98bb6c'
yellow = '#e6c384'
blue = '#7fb4ca'
magenta = '#938aa9'
cyan = '#7aa89f'
white = '#dcd7ba'

[colors.selection]
background = '#2d4f67'
foreground = '#c8c093'

[[colors.indexed_colors]]
index = 16
color = '#ffa066'

[[colors.indexed_colors]]
index = 17
color = '#ff5d62'

# NORD
#[colors.primary]
#background = "#2e3440"
#foreground = "#d8dee9"
#dim_foreground = "#a5abb6"
#
#[colors.cursor]
#text = "#2e3440"
#cursor = "#d8dee9"
#
#[colors.vi_mode_cursor]
#text = "#2e3440"
#cursor = "#d8dee9"
#
#[colors.selection]
#text = "CellForeground"
#background = "#4c566a"
#
#[colors.search.matches]
#foreground = "CellBackground"
#background = "#88c0d0"
#
#
#[colors.normal]
#black = "#3b4252"
#red = "#bf616a"
#green = "#a3be8c"
#yellow = "#ebcb8b"
#blue = "#81a1c1"
#magenta = "#b48ead"
#cyan = "#88c0d0"
#white = "#e5e9f0"
#
#[colors.bright]
#black = "#4c566a"
#red = "#bf616a"
#green = "#a3be8c"
#yellow = "#ebcb8b"
#blue = "#81a1c1"
#magenta = "#b48ead"
#cyan = "#8fbcbb"
#white = "#eceff4"
#
#[colors.dim]
#black = "#373e4d"
#red = "#94545d"
#green = "#809575"
#yellow = "#b29e75"
#blue = "#68809a"
#magenta = "#8c738c"
#cyan = "#6d96a5"
#white = "#aeb3bb"
#
